### ISSUE TITLE
ModuleNotFoundError: No module named 'usl'

### ISSUE THREAD

**Issue by diegolovison** [wip727/PyUSL#1]
Any reason why ?
```
/Users/dlovison/opt/anaconda3/envs/dg_usl/bin/python /Users/dlovison/PycharmProjects/dg_usl/example.py
Traceback (most recent call last):
  File "/Users/dlovison/PycharmProjects/dg_usl/example.py", line 3, in <module>
    from pyusl import usl
  File "/Users/dlovison/opt/anaconda3/envs/dg_usl/lib/python3.7/site-packages/pyusl/__init__.py", line 1, in <module>
    from usl import *;
ModuleNotFoundError: No module named 'usl'
```

**Comment by wip727** [comment]
Thanks for reporting this. The issue can be reproduced on python 3.6 and pyusl 0.0.3
I will push a quick release to fix this.
